  --DROP indices que ya no se usan
  DROP INDEX "IDX_AUDIT_MASTER_USER"
  ;
  
 
  DROP INDEX "SGT_ZONAS_CHK_NOMBRE" ON "SGT_ZONAS" ("NOMBRE") 
  ;
  DROP INDEX "SIGLAS_UNICA" ON "SGT_TIPO_EQUIPOS" ("SIGLAS") 
  ;
  DROP INDEX "SITIO_SIGLA_UNICOS" ON "SGT_SALAS" ("SITIO_ID", "SIGLAS") 
  ;
  
  --INDICES A CREAR
  CREATE INDEX "IDX_AUDIT_DETAIL_HIST" ON "AUDIT_DETAIL" ("TABLE_NAME", "COLUMN_NAME", "PK_VALUE", "AUDIT_ID") 
  ;
  CREATE INDEX "IDX_AUDIT_DETAIL_PK" ON "AUDIT_DETAIL" ("TABLE_NAME", "PK_VALUE", "AUDIT_ID" DESC) 
  ;
  CREATE INDEX "IDX_AUDIT_MASTER_ACTION" ON "AUDIT_MASTER" ("ACTION_TYPE", "TIMESTAMP" DESC) 
  ;
  CREATE INDEX "IDX_AUDIT_MASTER_TS" ON "AUDIT_MASTER" ("TIMESTAMP" DESC, "AUDIT_ID" DESC) 
  ;
  CREATE INDEX "IDX_AUDIT_MASTER_USER" ON "AUDIT_MASTER" ("APEX_USER", "TIMESTAMP" DESC) 
  ;
  CREATE UNIQUE INDEX "IDX_EQUIPOS_RACK_NOMBRE_UNIQ" ON "SGT_EQUIPOS" ("RACK_ID", UPPER("NOMBRE")) 
  ;
  CREATE UNIQUE INDEX "SGT_RACKS_SALA_NOMBRE_UNIQ" ON "SGT_RACKS" ("SALA_ID", UPPER("NOMBRE")) 
  ;
  CREATE UNIQUE INDEX "SGT_SALAS_SIGLAS_UNIQ" ON "SGT_SALAS" ("SITIO_ID", UPPER("SIGLAS")) 
  ;
  CREATE UNIQUE INDEX "SGT_INTERFACES_EQUIPO_NOMBRE_UNIQUE" ON "SGT_INTERFACES" ("EQUIPO_ID", UPPER("NOMBRE")) 
  ;
  CREATE UNIQUE INDEX "SITIO_SIGLA_UNICOS" ON "SGT_SALAS" ("SITIO_ID", UPPER("SIGLAS") )
  ;
  CREATE UNIQUE INDEX "SGT_ZONAS_CHK_NOMBRE" ON "SGT_ZONAS" (UPPER ("NOMBRE") )
  ;
  CREATE UNIQUE INDEX "SGT_SITIOS_SIGLAS_UNIK" ON "SGT_SITIOS" (UPPER("SIGLAS") )
  ;
  CREATE UNIQUE INDEX "SIGLAS_UNICA" ON "SGT_TIPO_EQUIPOS" (UPPER("SIGLAS")) 
  ;
  
  --Indices Existentes.
  CREATE INDEX "IDX_AUDIT_DETAIL_MASTER" ON "AUDIT_DETAIL" ("AUDIT_ID") 
  ;
  CREATE INDEX "IDX_AUDIT_DETAIL_TABLE" ON "AUDIT_DETAIL" ("AUDIT_ID", "TABLE_NAME") 
  ;
  CREATE INDEX "IDX_AUDIT_MASTER_DATE" ON "AUDIT_MASTER" ("TIMESTAMP") 
  ;
  CREATE INDEX "SGT_ENLACES_LOGICOS_I2" ON "SGT_ENLACES_LOGICOS" ("SITIO_A_ID", "EQUIPO_A_ID", "INTERFAZ_A_ID") 
  ;
  CREATE INDEX "SGT_ENLACES_LOGICOS_I3" ON "SGT_ENLACES_LOGICOS" ("SITIO_B_ID", "EQUIPO_B_ID", "INTERFAZ_B_ID") 
  ;
  CREATE INDEX "SGT_ENLACES_WAN_SERVICIO_I1" ON "SGT_ENLACES_WAN_SERVICIO" ("SERVICIO_ID") 
  ;
  CREATE INDEX "SGT_ENLACES_WAN_SERVICIO_I2" ON "SGT_ENLACES_WAN_SERVICIO" ("ENLACE_ID") 
  ;
  CREATE INDEX "SGT_SITIOS_ENLACE_WAN_I1" ON "SGT_SITIOS_ENLACE_WAN" ("SITIO_ID") 
  ;
  CREATE INDEX "SGT_SITIOS_ENLACE_WAN_I2" ON "SGT_SITIOS_ENLACE_WAN" ("ENLACE_WAN_ID") 
  ;
  CREATE UNIQUE INDEX "SGT_SITIOS_ENLACE_WAN_ID_PK" ON "SGT_SITIOS_ENLACE_WAN" ("ID") 
  ;
  CREATE INDEX "SGT_SITIOS_SERVICIO_I1" ON "SGT_SITIOS_SERVICIO" ("SITIO_ID") 
  ;
  CREATE INDEX "SGT_SITIOS_SERVICIO_I2" ON "SGT_SITIOS_SERVICIO" ("SERVICIO_ID") 
  ;
  CREATE UNIQUE INDEX "SGT_SITIOS_SERVICIO_ID_PK" ON "SGT_SITIOS_SERVICIO" ("ID") 
  ;

  