SELECT DBMS_METADATA.GET_DDL('TYPE', object_name) AS ddl_codigo FROM user_objects WHERE object_type = 'TYPE';
results:
CREATE OR REPLACE EDITIONABLE TYPE "WKSP_DTESC"."COORD_OBJ" AS OBJECT ( lat NUMBER, lon NUMBER )
CREATE OR REPLACE EDITIONABLE TYPE "WKSP_DTESC"."TABLA_IDS" as table of number