CREATE INDEX "IDX_AUDIT_DETAIL_MASTER" ON "AUDIT_DETAIL" ("AUDIT_ID") 
;
CREATE INDEX "IDX_AUDIT_DETAIL_TABLE" ON "AUDIT_DETAIL" ("TABLE_NAME") 
;
CREATE INDEX "IDX_AUDIT_MASTER_DATE" ON "AUDIT_MASTER" ("TIMESTAMP") 
;
CREATE INDEX "IDX_AUDIT_MASTER_USER" ON "AUDIT_MASTER" ("APP_USER") 
;
CREATE INDEX "SGT_ENLACES_LOGICOS_I2" ON "SGT_ENLACES_LOGICOS" ("SITIO_A_ID", "EQUIPO_A_ID", "INTERFAZ_A_ID") 
;
CREATE INDEX "SGT_ENLACES_LOGICOS_I3" ON "SGT_ENLACES_LOGICOS" ("SITIO_B_ID", "EQUIPO_B_ID", "INTERFAZ_B_ID") 
  ;
CREATE INDEX "SGT_ENLACES_WAN_SERVICIO_I1" ON "SGT_ENLACES_WAN_SERVICIO" ("SERVICIO_ID") 
  ;
CREATE INDEX "SGT_ENLACES_WAN_SERVICIO_I2" ON "SGT_ENLACES_WAN_SERVICIO" ("ENLACE_ID") 
  ;
CREATE UNIQUE INDEX "SGT_INTERFACES_EQUIPO_UNIQUE" ON "SGT_INTERFACES" ("EQUIPO_ID", "NOMBRE") 
  ;
CREATE INDEX "SGT_SITIOS_ENLACE_WAN_I1" ON "SGT_SITIOS_ENLACE_WAN" ("SITIO_ID") 
  ;
CREATE INDEX "SGT_SITIOS_ENLACE_WAN_I2" ON "SGT_SITIOS_ENLACE_WAN" ("ENLACE_WAN_ID") 
  ;
CREATE UNIQUE INDEX "SGT_SITIOS_ENLACE_WAN_ID_PK" ON "SGT_SITIOS_ENLACE_WAN" ("ID") 
  ;
CREATE INDEX "SGT_SITIOS_SERVICIO_I1" ON "SGT_SITIOS_SERVICIO" ("SITIO_ID") 
  ;
CREATE INDEX "SGT_SITIOS_SERVICIO_I2" ON "SGT_SITIOS_SERVICIO" ("SERVICIO_ID") 
  ;
CREATE UNIQUE INDEX "SGT_SITIOS_SERVICIO_ID_PK" ON "SGT_SITIOS_SERVICIO" ("ID") 
  ;
CREATE UNIQUE INDEX "SGT_SITIOS_SIGLAS_UNIK" ON "SGT_SITIOS" ("SIGLAS") 
  ;
CREATE UNIQUE INDEX "SGT_ZONAS_CHK_NOMBRE" ON "SGT_ZONAS" ("NOMBRE") 
  ;
CREATE UNIQUE INDEX "SIGLAS_UNICA" ON "SGT_TIPO_EQUIPOS" ("SIGLAS") 
  ;
CREATE UNIQUE INDEX "SITIO_SIGLA_UNICOS" ON "SGT_SALAS" ("SITIO_ID", "SIGLAS") 
  ;